EXP_NAME: "b5_3q_bs24_fp32"
FOLD: 0
DEVICE: 0
BS: 22
FP16: False
EPOCH:  10
MODEL:
  NAME: "CustomModel_v3"
  CFG:
    encoder: "tf_efficientnet_b5_ns"
    img_w: 256
    img_h: 256
    scale_cqt: True
    cqts_params: 
          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 32
            bins_per_octave: 8

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 16
            bins_per_octave: 4

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 128
            bins_per_octave: 24

TRANSFORM: 
  NAME: "src.transforms.minmax_turkey_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10
