EXP_NAME: "001_effnetb0_bandpass_sub_spec2_fp32_cos"
FOLD: 0
DEVICE: 0
BS: 64
FP16: False
EPOCH:  7
MODEL:
  NAME: "CustomModel_v1"
  CFG:
    encoder: "efficientnet_b0"
    img_w: 256
    img_h: 256
    sr: 2048
    fmin: 20 
    fmax: 1024
    hop_length: 32
    bins_per_octave: 8

TRANSFORM: 
  NAME: "src.transforms.minmax_sub_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10