EXP_NAME: "002_effnetb0_1"
FOLD: 0
DEVICE: 1
BS: 32
FP16: False
EPOCH:  10
MODEL:
  NAME: "CustomModel_v2"
  CFG:
    encoder: "efficientnet_b0"
    img_w: 256
    img_h: 256
    scale_cqt: False
    cqts_params: 
          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 32
            bins_per_octave: 8

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 128
            bins_per_octave: 24

TRANSFORM: 
  NAME: "src.transforms.minmax_turkey_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10
