EXP_NAME: "001_base_plus_bandpass"
# DEBUG: True
FOLD: 0
BS: 128
EPOCH:  10
MODEL:
  NAME: "Wavenet"
  CFG:
    in_channels: 6
TRANSFORM: 
  NAME: "src.transforms.minmax_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
  CFG:
    T_0: 5
    T_mult: 1