EXP_NAME: "003_wavenet_bandpass_fp16_bs_256_cos_10epoch"
FOLD: 0
BS: 256
FP16: True
EPOCH:  10
MODEL:
  NAME: "Wavenet"
TRANSFORM: 
  NAME: "src.transforms.minmax_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10