EXP_NAME: "009_rexnet150_bandpass_fp32_cos_5_radam"
FOLD: 0
BS: 100
FP16: False
EPOCH:  7
MODEL:
  NAME: "CustomModel_v1"
  CFG:
    encoder: "rexnet_150"
    img_w: 256
    img_h: 256
    sr: 2048
    fmin: 20 
    fmax: 1024
    hop_length: 32
    bins_per_octave: 8
TRANSFORM: 
  NAME: "src.transforms.minmax_bandpass_transform"
SCHEDULER:
  NAME: ""torch.optim.lr_scheduler.CosineAnnealingLR""
  CFG:
    T_max: 5
    eta_min: 0.00001
OPTIMIZER:
  NAME: "src.optimizers.RAdam"
  CFG:
    lr: 0.001