EXP_NAME: "020_effnetb0_fp32_big_spec_30-500"
FOLD: 0
BS: 128
FP16: False
EPOCH:  7
MODEL:
  NAME: "CustomModel_v1"
  CFG:
    encoder: "efficientnet_b0"
    img_w: 256
    img_h: 256
    sr: 2048
    fmin: 20 
    fmax: 1024
    hop_length: 8
    bins_per_octave: 24
TRANSFORM: 
  NAME: "src.transforms.minmax_bandpass_transform"
  CFG:
    lf: 30
    hf: 500

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 5
    eta_min: 0.00001