EXP_NAME: "031_effnetb0_bandpass_fp32_cos_restarts_15_clip0.5"
FOLD: 0
BS: 128
FP16: False
EPOCH:  15
TRAIN_FOLD: 3
GRAD_CLIP: 0.5
MODEL:
  NAME: "CustomModel_v1"
  CFG:
    encoder: "efficientnet_b0"
    img_w: 256
    img_h: 256
    sr: 2048
    fmin: 20 
    fmax: 1024
    hop_length: 32
    bins_per_octave: 8
TRANSFORM: 
  NAME: "src.transforms.minmax_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
  CFG:
    T_0: 4
    T_mult: 1
    # eta_min: 0.00001