EXP_NAME: "034_wavenetv2_bandpass_fp32_cos_10_best"
FOLD: 0
BS: 180
FP16: False
EPOCH:  12
MODEL:
  NAME: "Wavenet_v2"
TRANSFORM: 
  NAME: "src.transforms.minmax_bandpass_transform"

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10