EXP_NAME: "00_b0_128_5cqt"
FOLD: 0
BS: 64
FP16: False
EPOCH:  7
TRAIN_FOLD: -1

GRAD_CLIP: 
  START_EPOCH: 3
  THR: 0.5

MODEL:
  NAME: "CustomModel_v2"
  CFG:
    encoder: "efficientnet_b0"
    img_w: 128
    img_h: 128
    cqt_params: 
          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 32
            bins_per_octave: 8

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 128
            bins_per_octave: 24

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 128
            bins_per_octave: 4

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 16
            bins_per_octave: 24

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 16
            bins_per_octave: 4

TRANSFORM: 
  NAME: "src.transforms.minmax_turkey_bandpass_transform"
  CFG:
    lf: 30
    hf: 400

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10

N_SAVED: 4

TENSORBOARD_DIR: "/home/trytolose/rinat/kaggle/grav_waves_detection/logs/tensorboard_grid"