EXP_NAME: "08_512x512_seresnext50_f32"
FOLD: 0
BS: 28
FP16: False
EPOCH:  7
TRAIN_FOLD: -1

SCALER:
  NAME: "src.transforms.Scaler"
  MODE: "standart"
  MIN: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  MAX: [1.0152528,  1.0579135,  4.407389,   0.6678433,  0.6959216,  2.6014798,
 0.96952397, 0.99088365, 4.4576807,  0.67043734, 0.6968712,  2.6080358,
 1.0269003,  1.0014149,  4.6485667 ]



MODEL:
  NAME: "CustomModel_v2"
  USE_SCALER: True
  CFG:
    encoder: "seresnext50_32x4d"
    img_w: 512
    img_h: 512
    cqt_params: 
          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 32
            bins_per_octave: 8

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 128
            bins_per_octave: 24

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 128
            bins_per_octave: 4

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 16
            bins_per_octave: 24

          - sr: 2048
            fmin: 20 
            fmax: 1024
            hop_length: 16
            bins_per_octave: 4

TRANSFORM: 
  NAME: "src.transforms.minmax_turkey_bandpass_transform"
  CFG:
    lf: 30
    hf: 400

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 9

N_SAVED: 5

TENSORBOARD_DIR: "/home/trytolose/rinat/kaggle/grav_waves_detection/logs/tensorboard_grid"