EXP_NAME: "10_cwt"
FOLD: 0
BS: 64
FP16: False
EPOCH:  7
TRAIN_FOLD: 1

GRAD_CLIP: 
  START_EPOCH: 3
  THR: 0.5

SCALER:
  NAME: "src.transforms.Scaler"
  MODE: "standart"
  MIN: []
  MAX: []
  MEAN: []
  STD: []


MODEL:
  NAME: "CustomModel_CWT"
  USE_SCALER: True
  CFG:
    encoder: "efficientnet_b0"
    img_w: 128
    img_h: 128

TRANSFORM: 
  NAME: "src.transforms.minmax_turkey_bandpass_transform"
  CFG:
    lf: 30
    hf: 400

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingLR"
  CFG:
    T_max: 10

N_SAVED: 4

TENSORBOARD_DIR: "/home/trytolose/rinat/kaggle/grav_waves_detection/logs/tensorboard_grid"