EXP_NAME: "default_stack_pos_w"
FOLD: 0
BS: 128
EPOCH:  10
MODEL:
  NAME: "CustomModel_v0"
  ENCODER: "rexnet_100"
  IMG_SIZE: [256, 256]
TRANSFORM: 
  NAME: "src.transforms.dumb_stack_transform"
LOSS:
  NAME: "torch.nn.BCEWithLogitsLoss"
  CFG: 
    pos_weight: [2.]