EXP_NAME: "default_stack_512"
FOLD: 0
BS: 32
EPOCH:  10
MODEL:
  NAME: "CustomModel_v0"
  ENCODER: "rexnet_100"
  IMG_SIZE: [512, 512]
TRANSFORM: 
  NAME: "src.transforms.dumb_stack_transform"
LOSS:
  NAME: "torch.nn.BCEWithLogitsLoss"