hydra:
  run:
    dir: "."
  output_subdir: null

GPU: 0
DEBUG: False
EXP_NAME: "test"
FOLD: 0
STEPS_PER_EPOCH: 2000
BS: 128
NUM_WORKERS: 12
FP16: False
GRAD_CLIP: 
  START_EPOCH: 1000
  THR: 0.5
  
TRAIN_FOLD: -1

TRANSFORM: 
  NAME: "src.transforms.stack_turkey"
  CFG: {}

EPOCH: 10
MIXUP: False

LOSS:
  NAME: "torch.nn.BCEWithLogitsLoss"
  CFG: {}

MODEL:
  NAME: "src.model.CustomModel_v1"
  USE_SCALER: False
  CFG: {}
  CHECKPOINT: ""
  # ENCODER: "efficientnet_b0"
  # IMG_SIZE: [256, 256]

SCALER:
  NAME: "src.transforms.Scaler"
  MODE: "standart"
  MIN: []
  MAX: []
  MEAN: []
  STD: []

OPTIMIZER:
  NAME: "torch.optim.Adam"
  CFG:
    lr: 0.001

SCHEDULER:
  NAME: "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
  CFG: {}

N_SAVED: 5
CH_PATH: "/home/trytolose/rinat/kaggle/grav_waves_detection/weights"
TENSORBOARD_DIR: "/home/trytolose/rinat/kaggle/grav_waves_detection/logs/tensorboard"
INPUT_PATH: "/home/trytolose/rinat/kaggle/grav_waves_detection/input"