hydra:
  run:
    dir: "."
  output_subdir: null

EXP_NAME: "test"
FOLD: 0
STEPS_PER_EPOCH: 2000
BS: 128

EPOCH: 10

TRANSFORM: "src.transforms.stack_turkey"

MODEL:
  NAME: "src.model.CustomModel_v1"
  IMG_SIZE: [256, 256]

qtransform_params:
  sr: 2048
  fmin: 30 
  fmax: 400
  hop_length: 64
  bins_per_octave: 12
  filter_scale: 0.5

bandpass_param:
  lf: 30
  hf: 400
  order: 8 
  sr: 2048

cwt_params:
  widths: [10, 90, 0.5]
  wavelet: 'cmorlet'
  channels: 3
  filter_len: 4096